#这是配置文件，不要乱动

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useSSL=false
    username: root
    password: 123456
  application:
    name: Application
  mail:
    host: smtp.qq.com
    port: 587
    username: 1520131241@qq.com
    password: bgfvbdnkpzdvidic
    properties:
      mail:
        smtp:
          auth: true
  jpa:
    hibernate:
      ddl-auto: update


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.system.pojo

server:
  address: 0.0.0.0
  port: 8081

